# Use an official Node.js runtime as the base image

FROM node:19

# Set the working directory in the container

WORKDIR /app

# Copy the package.json and package-lock.json files to the container

COPY package\*.json ./

# Install the application's dependencies

RUN npm install

# Copy the rest of the application's files to the container

COPY . .

RUN apt-get update && apt-get install -y iputils-ping default-mysql-client

RUN npm install -g sequelize-cli

# Expose port 3000 to the host machine
ENTRYPOINT ["/bin/bash", "-c", "until mysqladmin ping -h $DB_HOST --silent; do echo 'Waiting for database to become available...'; sleep 1; done && npm start"]

# Expose port 3000 to the host machine
EXPOSE 3000
# Start the application